### ISSUE TITLE
Dependencies not available

### ISSUE THREAD

**Issue by nghowai** [leeper/tabulizer#16]
When I tried to install the package, the following error message appear:

Warning: dependencies ‘BiocInstaller’, ‘Rcompression’, ‘glmmADMB’, ‘lme4.0’, ‘cacheSweave’, ‘weaver’, ‘graph’, ‘Biobase’, ‘GenomicRanges’, ‘marray’, ‘affy’, ‘limma’, ‘Rcampdf’, ‘Rgraphviz’, ‘tm.lexicon.GeneralInquirer’, ‘ReportingTools’, ‘globaltest’, ‘R2wd’, ‘RDCOMClient’, ‘rhdf5’ are not available

and was unable to continue installation.

Would you please help with this issue? Thank you!

**Comment by leeper** [comment]
Try upgrading the latest version of ghit (v0.2.10), or use `devtools::install_github(c("leeper/tabulizerjars", "leeper/tabulizer"))`.
