### ISSUE TITLE
A parameter in extract_tables to assume row names and colnames from first row and column

### ISSUE THREAD

**Issue by hansthompson** [leeper/tabulizer#7]
If tables are coming in to R as matrices, Could the conversion to data.frames be made simpler with a parameter for assuming the first row or columns should be row and columns names?

**Comment by leeper** [comment]
Try setting `method = "data.frame"`. If you have a well-formed table, that should return a very nice data.frame with column names specified and row names as a column.

**Comment by pssguy** [comment]
The table i am sourcing  from looks well formed but it comes out as a list even when stipulating as a data.frame and when I coerce to data.frame the first row becomes the column headings

```
library(tidyverse)
library(tabulizer)
 extract_tables("https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812293", pages = 3, method="data.frame") %>% 
    as.data.frame()
```

![](https://cloud.githubusercontent.com/assets/2775918/21871857/d3be0750-d819-11e6-909a-5eec40b3a2b4.PNG)

I'm on v 0.1.22

**Comment by leeper** [comment]
@pssguy It's a list of data.frames:

```
> str(.)
List of 1
 $ :'data.frame':       52 obs. of  10 variables:
  ..$ Alabama: chr [1:52] "Alaska " "Arizona " "Arkansas " "California " ...
  ..$ X820   : chr [1:52] "73 " "770 " "466 " "3,074 " ...
  ..$ X4.849 : chr [1:52] "737 " "6,731 " "2,966 " "38,803 " ...
  ..$ X3.882 : chr [1:52] "532 " "4,882 " "2,112 " "24,813 " ...
  ..$ X5.367 : chr [1:52] "800 " "5,588 " "2,779 " "28,687 " ...
  ..$ X65.667: chr [1:52] "4,857 " "62,631 " "34,024 " "332,857 " ...
  ..$ X16.91 : num [1:52] 9.91 11.44 15.71 7.92 9.11 ...
  ..$ X21.13 : chr [1:52] "13.73 " "15.77 " "22.07 " "12.39 " ...
  ..$ X15.28 : num [1:52] 9.12 13.78 16.77 10.72 10.12 ...
  ..$ X1.25  : num [1:52] 1.5 1.23 1.37 0.92 1 0.8 1.26 0.65 1.24 1.04 ...
```

Just extract the first element using `[[` to get the data frame you want

**Comment by pssguy** [comment]
@leeper thansk for reply but I still haven't got it

```
 crash <- extract_tables("https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812293", pages = 3, method="data.frame") 

 crash[[1]]
                 Alabama    X820   X4.849   X3.882   X5.367    X65.667 X16.91 X21.13 X15.28 X1.25
1                Alaska      73      737      532      800      4,857    9.91 13.73    9.12  1.50

**Comment by oldi** [comment]
It has to be `output = "data.frame"`  - not method.
