### ISSUE TITLE
Better rstudio integration for extract_areas function

### ISSUE THREAD

**Issue by abresler** [leeper/tabulizer#8]
Hopefully from the rstudio team can help with this.

**Comment by leeper** [comment]
What issues are you encountering?

**Comment by abresler** [comment]
Really difficult to see and use the highlighter 
<img width="539" alt="screen shot 2016-05-03 at 10 02 56 am" src="https://cloud.githubusercontent.com/assets/740564/14985644/6109147c-1116-11e6-853a-c8f00bee49c4.png">

**Comment by leeper** [comment]
The cursor appears to be the same across graphics devices and is defined quite deeply inside the R source. I'm not sure there's going to be away to get around this.

**Comment by abresler** [comment]
Will see if I can find the right rstudio dev maybe JJ Allaire?

**Comment by leeper** [comment]
The answer may be to create a Shiny app. [`plotOutput()` offers a "brush" (drag) method](http://www.inside-r.org/packages/cran/shiny/docs/plotOutput) for highlighting an area of a plot. That will probably work better than the current approach and possibly resolve [platform-specific errors mentioned here](https://github.com/ropensci/onboarding/issues/42#issuecomment-223133535).

**Comment by leeper** [comment]
Another approach is [graphics events](https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/getGraphicsEvent.html), apparently, but I think this will require [`cairoDevice`](https://cran.r-project.org/web/packages/cairoDevice/index.html) to work on Mac.

**Comment by leeper** [comment]
Hey @abresler, I just added a little shiny widget thing as a hopefully better interface for when you're working within RStudio. Let me know if you have any reactions/suggestions.

**Comment by abresler** [comment]
You ROCK cannot wait to play with this!!
ᐧ


----------------------
*Alex Bresler*
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239
​ (cell)​

@abresler <http://twitter.com/abresler> | LinkedIn
<http://www.linkedin.com/in/abresler> | My Musings <http://asbcllc.com/blog>

**Comment by leeper** [comment]
I think I'm going to consider this closed, but I'll gladly reopen if any weird behavior emerges.
